/* tools/stamp.js — writes ui/version.js and cache-busts the module entry.
   Gives the running app a visible build id so "am I seeing the new code?"
   is answerable at a glance instead of by guesswork. */
import { writeFileSync, readFileSync } from "node:fs";
import { execSync } from "node:child_process";

const id = new Date().toISOString().slice(11, 19).replace(/:/g, "");
let sha = "local";
try { sha = execSync("git rev-parse --short HEAD").toString().trim(); } catch (e) { }
writeFileSync(new URL("../ui/version.js", import.meta.url),
  `/* GENERATED by tools/stamp.js */\nexport const BUILD = ${JSON.stringify(sha + "·" + id)};\n`);

const p = new URL("../index.html", import.meta.url);
let html = readFileSync(p, "utf8");
html = html.replace(/(\.\/ui\/app\.js)(\?v=[^"]*)?/, "./ui/app.js?v=" + sha + id);
html = html.replace(/(\.\/ui\/style\.css)(\?v=[^"]*)?/, "./ui/style.css?v=" + sha + id);
writeFileSync(p, html);
console.log("stamped build " + sha + "·" + id);
